#!/usr/bin/env python3
"""Generate deterministic Jekyll data for installed skills and modules."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"


def quote(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def skill_frontmatter(path: Path) -> dict[str, str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path.relative_to(ROOT)}: missing frontmatter")
    values: dict[str, str] = {}
    for line in lines[1:]:
        if line == "---":
            break
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        if key in {"name", "description"}:
            values[key] = value.strip().strip('"')
    if not values.get("name") or not values.get("description"):
        raise ValueError(f"{path.relative_to(ROOT)}: missing name or description")
    return values


def load_modules() -> list[dict[str, object]]:
    modules: list[dict[str, object]] = []
    for path in sorted((ROOT / "modules").glob("*/module.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        data["manifest_path"] = path.relative_to(ROOT).as_posix()
        modules.append(data)
    return modules


def render_skills(modules: list[dict[str, object]]) -> str:
    owners: dict[str, list[str]] = {}
    for module in modules:
        for skill in module.get("skills", []):
            owners.setdefault(skill["name"], []).append(str(module["id"]))

    lines = ["# Generated by docs/scripts/build_catalog.py. Do not edit."]
    for path in sorted((ROOT / "skills").glob("*/SKILL.md")):
        values = skill_frontmatter(path)
        skill_id = values["name"]
        lines.extend(
            [
                f"- id: {quote(skill_id)}",
                f"  name: {quote(skill_id.removeprefix('ai-sdlc-').replace('-', ' ').title())}",
                f"  description: {quote(values['description'])}",
                f"  path: {quote(path.relative_to(ROOT).as_posix())}",
                "  modules:",
                *[f"    - {quote(owner)}" for owner in sorted(owners.get(skill_id, []))],
            ]
        )
    return "\n".join(lines) + "\n"


def render_modules(modules: list[dict[str, object]]) -> str:
    lines = ["# Generated by docs/scripts/build_catalog.py. Do not edit."]
    for module in modules:
        harness = module.get("harness_api", {})
        lines.extend(
            [
                f"- id: {quote(module['id'])}",
                f"  name: {quote(str(module['id']).replace('-', ' ').title())}",
                f"  version: {quote(module['version'])}",
                f"  kind: {quote(module['kind'])}",
                f"  description: {quote(module['description'])}",
                f"  manifest_path: {quote(module['manifest_path'])}",
                f"  harness_min: {quote(harness.get('min', ''))}",
                f"  harness_max_exclusive: {quote(harness.get('max_exclusive', ''))}",
                "  requires:",
                *[f"    - {quote(item)}" for item in module.get("requires", [])],
                "  skills:",
                *[f"    - {quote(item['name'])}" for item in module.get("skills", [])],
            ]
        )
    return "\n".join(lines) + "\n"


def generate(check: bool = False) -> int:
    modules = load_modules()
    outputs = {
        DOCS / "_data" / "skills.yml": render_skills(modules),
        DOCS / "_data" / "modules.yml": render_modules(modules),
    }
    drift: list[str] = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if drift:
        print("Catalog drift: " + ", ".join(drift))
        return 1
    print(f"Catalog ready: {len(list((ROOT / 'skills').glob('*/SKILL.md')))} skills, {len(modules)} modules")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated data is stale")
    args = parser.parse_args()
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
